# Generated by Django 4.2.7 on 2023-12-05 13:38

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=755)),
                ('venue', models.CharField(max_length=755)),
                ('sheet', models.FileField(upload_to=events.models.sheet_rename)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_featured_photo', models.ImageField(upload_to=events.models.ticket_featured_photo_rename)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('sno', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('encoded_bar_code', models.CharField(blank=True, max_length=255, null=True)),
                ('event_attended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('e_ticket', models.ImageField(blank=True, null=True, upload_to=events.models.e_ticket_rename)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
